### ISSUE TITLE
[ Early Review ] Why a Scene?

### ISSUE THREAD

**Issue by Xananax** [Ryan-Mirch/Interactables-Demo#2]
https://github.com/Ryan-Mirch/Interactables-Demo/blob/d08aa216b98007e13f0bd56b1b098a8320bc6aa9/Interactable/Interactable.gd#L5

It seems like this could just as well be a `Label.new()`. Is there any benefit in making it a scene?

See also #2

**Comment by Ryan-Mirch** [comment]
right so i made it a scene so i could customize its look, if it was made in
code its hard to know what itll look like until you run it.
