### ISSUE TITLE
[ Early Review ] How about not having the interactable handle the Label?

### ISSUE THREAD

**Issue by Xananax** [Ryan-Mirch/Interactables-Demo#3]
https://github.com/Ryan-Mirch/Interactables-Demo/blob/d08aa216b98007e13f0bd56b1b098a8320bc6aa9/Interactable/Interactable.gd#L12-L15

See also #1

Seems to me like the interactable is not supposed to display a label at all.

Suppose:
- Player cannot use item unless they have another item (e.g., key for door)
- Player cannot use item unless they have specific stats
- Prompt needs to change on different devices ("touch" vs "press")
- Prompt needs to change depending on key binds
- Prompt needs to display images ("press ⊗ to interact")
- There are multiple objects that can be interacted with, and the player controller needs to decide on priorities
- etc

Furthermore, you may want to place the label on a CanvasLayer for example.

For all those reasons, I think we can dispatch a signal or call a function to an autoload, the autoload then handles the rest.

```mermaid
flowchart LR

Interactable --> |ready to interact| UI
UI --> |Interacted| Interactable
```

**Comment by Ryan-Mirch** [comment]
Ok so make an autoload that handles displaying the prompts? i like that.
